# Generated by Django 3.2.7 on 2021-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='rollno',
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
