# Generated by Django 3.2.7 on 2021-11-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211112_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='email',
        ),
    ]
